semi: true
singleQuote: false
trailingComma: es5
arrowParens: always
tabWidth: 2
useTabs: false
quoteProps: as-needed
jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
overrides:
  - files: "*.steps.*"
    options:
      tabWidth: 4
