name: Node.js CI Action

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  build:
    name: Node.js Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test
